name: ally
description: "A student tracking app. From RSHS III"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 3.15.1
  firebase_auth: 5.6.2
  cloud_firestore: 5.6.11
  firebase_storage: ^12.3.9
  firebase_app_check: ^0.3.0+1
  flutter_map: 8.2.1
  flutter_map_tile_caching: ^10.1.1
  latlong2: 0.9.1
  http: ^1.5.0-beta
  font_awesome_flutter: 10.8.0
  geolocator: 14.0.2
  geocoding: 4.0.0
  flutter_local_notifications: ^17.2.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  share_plus: ^10.0.2
  path_provider: ^2.1.5
  flutter_background_service: ^5.0.6
  flutter_background_service_android: ^6.0.2
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Or your image file name
    - assets/background.png

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
